# ================================
# CONFIGURAÇÃO DO SISTEMA GOOGL
# ================================

# ===== MANAGER (portátil) =====
manager.ip=192.168.1.66
manager.port=8182

# ===== GATEWAY (fixo) =====
gateway.ip=192.168.1.183
gateway.port=8186

# ===== BARRELS =====
# Cada máquina tem o seu próprio barrel
barrel.1.ip=192.168.1.183
barrel.1.port=8183
barrel.2.ip=192.168.1.66
barrel.2.port=8184

# ===== DOWNLOADERS =====
# Um por máquina, correspondente ao barrel
downloader.1.ip=192.168.1.183
downloader.2.ip=192.168.1.66
