# Spring Boot 
server.address=172.20.10.2
server.port=8080
spring.application.name=googol-web

# Thymeleaf
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

# Ollama
ollama.url=http://localhost:11434

# Logging
logging.level.root=INFO
logging.level.web=DEBUG
