# Spring Boot Configuration
server.port=8080
spring.application.name=googol-web

# Thymeleaf Configuration
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

# RMI Configuration
rmi.gateway.host=localhost
rmi.gateway.port=8186

# Logging
logging.level.root=INFO
logging.level.web=DEBUG
