# Spring Boot 
server.port=8080
spring.application.name=googol-web

# Thymeleaf
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/

# RMI
rmi.gateway.host=localhost
rmi.gateway.port=8186

# OpenAI(deixar vazio se não tiver API key)
# Chave em: https://platform.openai.com/account/api-keys
openai.api.key=CHAVE_REMOVIDA
openai.api.model=gpt-3.5-turbo

# Logging
logging.level.root=INFO
logging.level.web=DEBUG
