# ================================
# CONFIGURAÇÃO DO SISTEMA GOOGL
# ================================

# ===== MANAGER (portátil) =====
manager.ip=localhost
manager.port=8182

# ===== GATEWAY (fixo) =====
gateway.ip=localhost
gateway.port=8186

# ===== BARRELS =====
# Cada máquina tem o seu próprio barrel
barrel.1.ip=localhost
barrel.1.port=8183
barrel.2.ip=localhost
barrel.2.port=8184

# ===== DOWNLOADERS =====
# Um por máquina, correspondente ao barrel
downloader.1.ip=localhost
downloader.2.ip=localhost
