# ================================
# CONFIGURAÇÃO DO SISTEMA GOOGL
# ================================

# ===== MANAGER (portátil) =====
manager.ip=172.20.10.2
manager.port=8182

# ===== GATEWAY (fixo) =====
gateway.ip=172.20.10.7
gateway.port=8186

# ===== BARRELS =====
# Cada máquina tem o seu próprio barrel
barrel.1.ip=172.20.10.7
barrel.1.port=8183
barrel.2.ip=172.20.10.2
barrel.2.port=8184

# ===== DOWNLOADERS =====
# Um por máquina, correspondente ao barrel
downloader.1.ip=172.20.10.7
downloader.2.ip=172.20.10.2
